package com.parameter;
 
import org.apache.poi.ss.usermodel.*;
import java.io.FileInputStream;
import java.io.IOException;
 
public class ExcelReader {
 
    public static Object[][] readExcel(String filePath, String sheetName) {
 
        try (FileInputStream fis = new FileInputStream(filePath);
             Workbook workbook = WorkbookFactory.create(fis)) {
 
            Sheet sheet = workbook.getSheet(sheetName);
            if (sheet == null) {
                throw new RuntimeException("Sheet not found: " + sheetName);
            }
            int totalRows = sheet.getPhysicalNumberOfRows();
            int totalCols = sheet.getRow(0).getLastCellNum();
 
            Object[][] data = new Object[totalRows - 1][totalCols];
 
            for (int i = 1; i < totalRows; i++) {
                Row row = sheet.getRow(i);
 
                for (int j = 0; j < totalCols; j++) {
                    Cell cell = (row == null) ? null : row.getCell(j);
 
                    data[i - 1][j] = getCellValue(cell);
                }
            }
            return data;
 
        } catch (IOException e) {
            throw new RuntimeException("Unable to read Excel file: " + filePath, e);
        }
    }
    // Converts ANY type of cell to String
    private static Object getCellValue(Cell cell) {
 
        if (cell == null) {
            return "";
        }
        CellType type = cell.getCellType();
        return switch (type) {
            case STRING -> cell.getStringCellValue().trim();
            case NUMERIC -> (DateUtil.isCellDateFormatted(cell))
                    ? cell.getDateCellValue().toString()
                    : String.valueOf((long) cell.getNumericCellValue());
            case BOOLEAN -> String.valueOf(cell.getBooleanCellValue());
            case FORMULA -> cell.getRichStringCellValue().getString();
            case BLANK, _NONE, ERROR -> "";
            default -> "";
        };
    }
}